config/routes.rb
Savant::Application.routes.draw do
  namespace :admin do
    resources :posts
    resources :images, only: [:create]
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/admin/images_controller.rb
module Admin
  class ImagesController < ApplicationController

    def create
      uploader = SirTrevorImageUploader.new

      if uploader.store! params[:attachment][:file]
        render json: uploader.as_json, status: 200
      else
        render :json => uploader.errors, status: 500
      end

    end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < ApplicationController

    def index
      @posts = Post.all
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new post_params

      if @post.save
        redirect_to admin_posts_path
      else
        render :new
      end
    end

    def edit
      @post = Post.find params[:id]
    end

    def update
      @post = Post.find params[:id]

      if @post.update_attributes post_params
        redirect_to admin_posts_path
      else
        render :edit
      end
    end

    def destroy
    end

  private
    def post_params
      params.require(:post).permit(:title, :content)
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |f| %>

  <div class="form__item">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form__item">
    <%= f.label :content %>
    <%= f.text_field :content, class: 'js-st-instance' %>
  </div>

  <%= f.submit "Save" %>

<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing <%= @post.title %></h1>

<%= render "form" %>

app/views/admin/posts/index.html.erb
<% @posts.each do |post| %>
  <%= link_to post.title, edit_admin_post_path(post) %>
<% end %>

app/views/admin/posts/new.html.erb
<h1>Create a new post</h1>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Savant</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
  <%= javascript_include_tag "application" %>
</body>
</html>